import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {PDFViewer} from "@react-pdf/renderer";
import styles from '../styles/Home.module.css'
import CvDocument from "../sec/components/CvDocument";
import React, {useEffect, useMemo, useState} from "react";
import CvDocumentOnePage from "../sec/components/CvDocument/CvDocumentOnePage";

const Home: NextPage = () => {
  const [showFullPdf, setShowFullPdf] = useState(false);
  const [showOnePagePdf, setShowOnePagePdf] = useState(false);
  // useEffect(() => {
  //   setShowFullPdf(true)
  // }, [])

  const cvDocumentElement = useMemo(() => {
    if (showFullPdf) {
      return <CvDocument />;
    }

    if (showOnePagePdf) {
      return <CvDocumentOnePage />
    }

    return null;
  }, [showFullPdf, showOnePagePdf]);

  const handleCloseClick = () => {
    setShowFullPdf(false);
    setShowOnePagePdf(false);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Radu Nemerenco CV</title>
        <meta name="description" content="Generated by create next app, powered by @react-pdf/renderer" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my CV website
        </h1>

        {!!cvDocumentElement && (
          <div style={{position: 'fixed', width: '100vw', height: '100vh'}}>
            <PDFViewer style={{position: 'absolute', width: '100vw', height: '100vh'}}>
              {cvDocumentElement}
            </PDFViewer>
            <a
              style={{
                position: "fixed",
                bottom: 15,
                right: 15,
                width: 30,
                height: 30,
                borderRadius: 20,
                background: '#c2c2c2',
                color: '#2a2a2a',
                display: 'flex',
                justifyContent: 'center',
                alignItems: "center",
                cursor: "pointer"
              }}
              role={"button"}
              onClick={handleCloseClick}
            >
              X
            </a>
          </div>
        )}
        <p className={styles.description}>
          Choose one by clicking the cards below{' '}
          {/*<code className={styles.code}>pages/index.tsx</code>*/}
        </p>

        <div className={styles.grid}>
          <a
            onClick={() => setShowOnePagePdf(true)}
            className={styles.card}
          >
            <h2>One Page CV &rarr;</h2>
            <p>This is the One Page CV - short version.</p>
          </a>

          <a
            onClick={() => setShowFullPdf(true)}
            className={styles.card}
            role={"button"}
          >
            <h2>Full CV &rarr;</h2>
            <p>This is the full version of the CV.</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
